=== abhii988/Online-Vehicle-Management-System/catalog_18029801.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!--Creating schema for the 'Shop' element which is of complex type and is giving reference to its child elements, which is in sequencial order.-->
	<xs:element name="Shop">
		<xs:complexType>
			<xs:sequence>
				<!--Referencing the elements present in the parent element.-->
				<xs:element ref="header"/>
				<xs:element ref="Items_Available"/>
				<xs:element ref="footer"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--Creating schema for the header element which is of complex type and is giving reference to its child elements which is in sequencial order.-->
	<xs:element name="header">
		<xs:complexType>
			<xs:sequence>
				<!--Referencing the elements present in the parent element.-->
				<xs:element ref="Logo"/>
				<xs:element ref="Name"/>
				<xs:element ref="Address"/>
				<xs:element ref="Website"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--Creating schema for the child elements of 'header' element.-->
	<xs:element name="Logo" type="xs:string"/>
	<xs:element name="Name" type="xs:string"/>
	<xs:element name="Address" type="xs:string"/>
	<xs:element name="Website" type="xs:string"/>
	<!--Creating schema for the 'Items_Available' element which is of complex type and is giving reference to its child elements which is in sequencial order.-->
	<xs:element name="Items_Available">
		<xs:complexType>
			<xs:sequence>
				<!--Here, 'minOccurs="0"' and 'maxOccurs="unbounded"' means that the data is repeated more that once.-->
				<xs:element ref="Item" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--Creating schema for the 'Item' element which is of complex type and is giving reference to its child elements which is in sequencial order.-->
	<xs:element name="Item">
		<xs:complexType>
			<xs:sequence>
				<!--Referencing the elements present in the parent element.-->
				<xs:element ref="Item_Number"/>
				<xs:element ref="Brand_Name"/>
				<xs:element ref="Brand_Logo"/>
				<xs:element ref="Car_Type"/>
				<xs:element ref="Car_Image"/>
				<xs:element ref="Description"/>
				<xs:element ref="Quantity"/>
				<xs:element ref="Price"/>
				<xs:element ref="Car_Info"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--Creating schema for the child elements of 'Item' element.-->
	<xs:element name="Item_Number" type="xs:integer"/>
	<xs:element name="Brand_Name" type="xs:string"/>
	<xs:element name="Brand_Logo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<!--Here, 'Brand_Logo' element has 'id' as an attribute and is of string type.-->
					<xs:attribute name="id" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Car_Type" type="xs:string"/>
	<xs:element name="Car_Image">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<!--Here, 'Car_Image' element has 'id' as an attribute and is of string type.-->
					<xs:attribute name="id" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Description" type="xs:string"/>
	<xs:element name="Quantity">
		<xs:simpleType>
            <!--Adding restriction to 'Quantity' element.-->
            <xs:restriction base="xs:integer">
            	<!--Defining a pattern for restriction using regex.-->
                <xs:pattern value="[0-9]{1,2}" /> 
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
	<xs:element name="Price">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<!--Here, 'Price' element has 'currency' as an attribute and is of string type.-->
					<xs:attribute name="currency" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!--Creating schema for the 'Car_Info' element which is of complex type and is giving reference to its child elements which is in sequencial order.-->
	<xs:element name="Car_Info">
		<xs:complexType>
			<xs:sequence>
				<!--Referencing the elements present in the parent element.-->
				<!--Here, the elements 'Engine, Battery_Capacity, Infotainment_System, Insurance, Camera' are optional elements, and are repeated more that once.-->
				<xs:element ref="Manufacturer"/>
				<xs:element ref="Model"/>
				<xs:element ref="Chassis_No"/>
				<xs:element ref="Engine" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Battery_Capacity" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Fuel_Type"/>
				<xs:element ref="Infotainment_System" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Insurance" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Camera" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Color"/>
				<xs:element ref="Weight"/>
				<xs:element ref="Mfg_Year"/>
				<xs:element ref="Used_For"/>
			</xs:sequence>
			<!--Here, 'Car_Info' element has 'Type' as an optional attribute and is of string type.-->
			<xs:attribute name="Type" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!--Creating schema for the child elements of 'Car_Info' element.-->
	<xs:element name="Manufacturer" type="xs:string"/>
	<xs:element name="Model" type="xs:string"/>
	<xs:element name="Chassis_No" type="xs:string"/>
	<xs:element name="Engine" type="xs:string"/>
	<xs:element name="Battery_Capacity" type="xs:string"/>
	<xs:element name="Fuel_Type">
		<xs:simpleType>
            <!--Adding restriction to 'Quantity' element.-->
            <xs:restriction base="xs:string">
            	<!--Defining a pattern for restriction using regex.-->
                <xs:enumeration value="Gas"/>
                <xs:enumeration value="Hybrid"/>
                <xs:enumeration value="Electric"/>
            </xs:restriction>
        </xs:simpleType>
	</xs:element>
	<xs:element name="Infotainment_System" type="xs:string"/>
	<xs:element name="Insurance" type="xs:string"/>
	<xs:element name="Camera" type="xs:string"/>
	<xs:element name="Color" type="xs:string"/>
	<xs:element name="Weight">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unit" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Mfg_Year" type="xs:integer"/>
	<xs:element name="Used_For">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<!--Here, 'Used_For' element has 'time' as an attribute and is of string type.-->
					<xs:attribute name="time" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!--Creating schema for the 'footer' element which is of complex type and is giving reference to its child elements which is in random order.-->
	<xs:element name="footer">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Telephone_No"/>
				<xs:element ref="Email"/>
				<xs:element ref="FB"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<!--Creating schema for the child elements of 'footer' element.-->
	<xs:element name="Telephone_No" type="xs:string"/>
	<xs:element name="Email" type="xs:string"/>
	<xs:element name="FB" type="xs:string"/>
</xs:schema>

=== abhii988/Online-Vehicle-Management-System/catalog_18029801.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Author: Abhishek Gupta-->
<!--Giving location to the CSS file.-->
<?xml-stylesheet type="text/css" href="catalog_18029801.css"?> 
<!--Declaring root 'Shop' element and giving location to the schema document.-->
<Shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_18029801.xsd">
	<!--Declaring header element where logo, name, locaiton and Website of the shop is kept.-->
	<header>
        <Logo/>
        <Name>Baluwatar Auto Dealership Pvt. Ltd.</Name>
        <Address>Baluwatar, Kathmandu</Address>
        <Website>www.baluwatarauto.com</Website>
    </header>
	<!--Declaring elements of cars available in the shop.-->
	<Items_Available>
		<!--Declaring child elements of the parent element 'Item'.-->
		<Item>
			<!--Declaring elements of each cars along with their number, brand name, logo, car type, car image, description, quantity and price.-->
			<Item_Number>1</Item_Number>
			<Brand_Name>Toyota</Brand_Name>
			<Brand_Logo id="b1"/>
			<Car_Type>Sedan</Car_Type>
			<Car_Image id="i1"/>
			<Description>This car has been sold by Toyota since the year of 1982 till now. It is one of the most selling model of Toyota.</Description>
			<Quantity>1</Quantity>
			<Price currency="Rs. ">2,800,000</Price>
			<!--Optional data fields in the parent element 'Car_Info' are 'Engine, Battery_Capacity, Infotainment_System, Insurance, Camera' elements.-->
			<Car_Info Type="Gas">
				<!--Declaring elements of each cars along with their manufacturer, model, chassis no., engine, battery capacity, fuel type, infotainment system, insurance, camera, color, weight, mfg year and used for.-->
				<Manufacturer>Toyota Motor Corp.</Manufacturer>
				<Model>Camry</Model>
				<Chassis_No>1HGBH41JXMN109186</Chassis_No>
				<Engine>2.5L</Engine>
				<Fuel_Type>Gas</Fuel_Type>
				<Camera>Dash Cam</Camera>
				<Color>White</Color>
				<Weight unit="kg">1,130</Weight>
				<Mfg_Year>2018</Mfg_Year>
				<Used_For time="years">2</Used_For>
			</Car_Info>
		</Item>
		<Item>
			<Item_Number>2</Item_Number>
			<Brand_Name>Mercedes-Benz</Brand_Name>
			<Brand_Logo id="b2"/>
			<Car_Type>Sports</Car_Type>
			<Car_Image id="i2"/>
			<Description>This car is an limited edition electric variant of SLS AMG series introduced by Mercedes in 2013.</Description>
			<Quantity>1</Quantity>
			<Price currency="Rs. ">20,500,000</Price>
			<Car_Info Type="Electric">
				<Manufacturer>Daimler AG</Manufacturer>
				<Model>SLS AMG Electric Drive</Model>
				<Chassis_No>1GNCS18Z3M0115561</Chassis_No>
				<Battery_Capacity>60kWh</Battery_Capacity>
				<Fuel_Type>Electric</Fuel_Type>
				<Infotainment_System>Android Auto</Infotainment_System>
				<Insurance>3rd Party</Insurance>
				<Camera>Dash and Backup Camera</Camera>
				<Color>Chrome Blue</Color>
				<Weight unit="kg">2110</Weight>
				<Mfg_Year>2013</Mfg_Year>
				<Used_For time="years">5</Used_For>
			</Car_Info>
		</Item>
		<Item>
			<Item_Number>3</Item_Number>
			<Brand_Name>Hyundai</Brand_Name>
			<Brand_Logo id="b3"/>
			<Car_Type>Hatchback</Car_Type>
			<Car_Image id="i3"/>
			<Description>This is a gas plus electric, hybrid car which is one of the best in the market.</Description>
			<Quantity>1</Quantity>
			<Price currency="Rs. ">4,500,000</Price>
			<Car_Info Type="Hybrid">
				<Manufacturer>Hyundai Motor Group</Manufacturer>
				<Model>Ioniq</Model>
				<Chassis_No>1HGCV1F39JA172420</Chassis_No>
				<Engine>1.6L</Engine>
				<Battery_Capacity>8.9kWh</Battery_Capacity>
				<Fuel_Type>Hybrid</Fuel_Type>
				<Infotainment_System>Multi-Info Display</Infotainment_System>
				<Camera>Backup Camera</Camera>
				<Color>White</Color>
				<Weight unit="kg">1,360</Weight>
				<Mfg_Year>2016</Mfg_Year>
				<Used_For time="years">3</Used_For>
			</Car_Info>
		</Item>
		<Item>
			<Item_Number>4</Item_Number>
			<Brand_Name>Audi</Brand_Name>
			<Brand_Logo id="b4"/>
			<Car_Type>SUV</Car_Type>
			<Car_Image id="i4"/>
			<Description>This is a crossover SUV that is completely electric built with Audi DNA.</Description>
			<Quantity>1</Quantity>
			<Price currency="Rs. ">30,000,000</Price>
			<Car_Info Type="Electric">
				<Manufacturer>Volkswagen Group</Manufacturer>
				<Model>E-tron</Model>
				<Chassis_No>1G1YZ23J9P5803427</Chassis_No>
				<Battery_Capacity>95kWh</Battery_Capacity>
				<Fuel_Type>Gas</Fuel_Type>
				<Infotainment_System>Apple CarPlay</Infotainment_System>
				<Insurance>Full</Insurance>
				<Camera>Dash and Backup Camera</Camera>
				<Color>Azure Blue</Color>
				<Weight unit="kg">2,560</Weight>
				<Mfg_Year>2019</Mfg_Year>
				<Used_For time="years">2</Used_For>
			</Car_Info>
		</Item>
		<Item>
			<Item_Number>5</Item_Number>
			<Brand_Name>Maruti Suzuki</Brand_Name>
			<Brand_Logo id="b5"/>
			<Car_Type>4x4 Off-Road</Car_Type>
			<Car_Image id="i5"/>
			<Description>This is a Suzuki Jimny SJ40/410 series based 4WD off-roading vehicle, one of the best off-road car.</Description>
			<Quantity>1</Quantity>
			<Price currency="Rs. ">1,500,000</Price>
			<Car_Info Type="Gas">
				<Manufacturer>Suzuki Motor Corp.</Manufacturer>
				<Model>Gypsy</Model>
				<Chassis_No>1HGCM82633A004352</Chassis_No>
				<Engine>1.0L</Engine>
				<Fuel_Type>Gas</Fuel_Type>
				<Color>Pearl White</Color>
				<Weight unit="kg">1,040</Weight>
				<Mfg_Year>2002</Mfg_Year>
				<Used_For time="years">12</Used_For>
			</Car_Info>
		</Item>
	</Items_Available>
    <footer>
        <Telephone_No>+977-1-4418888</Telephone_No>
        <Email>baluwatarautodealership@gmail.com</Email>
        <FB>www.facebook.com/baluwatarautodealership</FB>
    </footer>
</Shop>
